[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
]
[invariant]
invariant_runs = 10000
depth = 15
fail_on_revert = false

[fuzz]
runs = 5000
optimizer = true
optimizer_runs = 200
verbosity = 2


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
